name: cleanup

on:
  pull_request:
    types: [ closed ]

jobs:
  delete-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        scenario: [ 'success', 'failure' ]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm run build && npm run package

      - name: extract branch name
        id: get_branch
        shell: bash
        env:
          PR_HEAD: ${{ github.head_ref }}
        run: echo "branch=$(echo ${PR_HEAD#refs/heads/} | tr / -)" >> "$GITHUB_OUTPUT"

      - name: delete environment
        uses: ./
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: integration-test-${{ steps.get_branch.outputs.branch }}-${{ matrix.scenario }}
          debug: true
