name: cleanup

on:
  pull_request:
    types: [ closed ]

jobs:
  delete-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        scenario: [ 'success', 'failure' ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f  # v6
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm run build && npm run package

      - name: extract branch name
        id: get_branch
        shell: bash
        env:
          PR_HEAD: ${{ github.head_ref }}
        run: echo "branch=$(echo ${PR_HEAD#refs/heads/} | tr / -)" >> "$GITHUB_OUTPUT"

      - name: delete environment
        uses: ./
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: integration-test-${{ steps.get_branch.outputs.branch }}-${{ matrix.scenario }}
          debug: true
